### ISSUE TITLE
Routing error to /admin/products/variants

### ISSUE THREAD

**Issue by pddo** [citrus/spree_wholesale#8]
I get this error when I go to "variants" sub-menu in page edit products (admin panel):

   Routing Error
   undefined local variable or method `new_action' for Admin::VariantsController:Class

Others sub-menu are ok, but only this.
I've tried to debug and found out the error's source is the class in admin/resouce_controller.rb, then I temporary removed it from project and "variants" submenu came back to work. 
I new to Rails so I don't really understand how this class affects the routes.

Is there any suggest?

Thanks

**Comment by citrus** [comment]
Which version of Spree are you on? spree_wholesale hasn't been updated to work with Spree 0.70.0 and above..

**Comment by pddo** [comment]
Yeah, I'm using spree 0.70.1. Because this extension is important for my project, maybe I have to figure out how to fix temporary this bug and wait new update from spree_wholesale.

Thanks!

**Comment by mcgoooo** [comment]
I also see this issue, do you have any idea where to start with this?

<edit> 
i tried removing the resource controller as the only important thing i could see was the li8n, it had just got out of sync with the original resource controller. The errors are now occurring in the pagination, but i'm not too sure how i would sort that.
</edit>

**Comment by citrus** [comment]
When using `spree_wholesale/master` @ 7546c6c718e6c55446ab6d31eea9a7de768ed4e5  does this issue still occur?
